CREATE TABLE IF NOT EXISTS `ACCOUNT` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT
  , `USERNAME` VARCHAR(255) UNIQUE
  , PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `CUSTOMER` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT
  , `FIRST_NAME` VARCHAR(255) NULL DEFAULT NULL
  , `LAST_NAME` VARCHAR(255) NULL DEFAULT NULL
  , `ACCOUNT_ID` BIGINT NOT NULL UNIQUE
  , PRIMARY KEY (`ID`)
  , FOREIGN KEY (`ACCOUNT_ID`)
    REFERENCES `demo`.`ACCOUNT`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

