CREATE TABLE IF NOT EXISTS PRODUCT (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT
  , NAME VARCHAR(255)
  , CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
  , UPDATED_AT DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
  , DELETED_AT DATETIME DEFAULT NULL
  , CONSTRAINT uk_product_name UNIQUE(name)
);

CREATE TABLE IF NOT EXISTS `ORDER` (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT
  , NAME VARCHAR(255)
  , CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
  , UPDATED_AT DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
  , DELETED_AT DATETIME DEFAULT NULL
  , CONSTRAINT uk_order_name UNIQUE(NAME)
);

CREATE TABLE IF NOT EXISTS `user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT
  , `username` VARCHAR(255) UNIQUE
  , `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
  , `created_by` BIGINT DEFAULT NULL
  , `updated_at` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
  , `updated_by` BIGINT DEFAULT NULL
  , `deleted_at` DATETIME DEFAULT NULL
  , `deleted_by` BIGINT DEFAULT NULL
  , PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `user_info` (
  `user_id` BIGINT NOT NULL
  , `first_name` VARCHAR(255)
  , `last_name` VARCHAR(255)
  , PRIMARY KEY (`user_id`)
  , FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
);
